tagger_prac/tagger/urls.py
from django.urls import path, include
from rest_framework import routers
from tagger import views

router = routers.DefaultRouter()
router.register(r'rosters', views.RosterView, 'roster')
router.register(r'player', views.PlayerView, 'player')
router.register(r'game', views.GameView, 'game')
router.register(r'inning', views.InningView, 'inning')
router.register(r'atbat', views.AtBatView, 'atbat')
router.register(r'pitch', views.PitchView, 'pitch')

from . import views

app_name = 'tagger'
urlpatterns = [
    #create a player
    path('home/', views.home, name='home'),
    path('player_index/', views.player_index.as_view(), name='player_index'),
    path('roster_index/', views.roster_index.as_view(), name='roster_index'),
    path('create_roster/', views.create_roster.as_view(), name='create_roster'),
    #path('create_player/', views.create_player.as_view(), name='create_player'),
    path('roster/add_player/<int:roster_id>/', views.add_player, name='add_player'),
    path('player_details/<int:pk>/', views.player_details.as_view(), name='player_details'),
    path('roster_details/<int:pk>/', views.roster_details.as_view(), name='roster_details'),
    path('create_game/', views.create_game, name='create_game'),
    path('game_index/', views.game_index.as_view(), name='game_index'),
    path('game_details/<int:pk>/', views.game_details.as_view(), name='game_details'),
    #path('game_details/add_play/<int:game_id>/', views.add_play, name='add_play'),
    #path('play_details/<int:pk>/', views.play_details.as_view(), name='play_details'),
    path('api/', include(router.urls)),
]

tagger_prac/tagger_prac/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tagger/', include('tagger.urls')),
]

tagger_prac/tagger/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone

# our Roster model
class Roster(models.Model):
    roster_name = models.CharField(max_length=50)
    num_players = models.IntegerField(default=0)
    player = models.ForeignKey('Player', on_delete=models.CASCADE, null=True, related_name='roster_set')

    def get_absolute_url(self):
        return reverse('tagger:roster_details', kwargs={'pk': self.pk})

# our Player model, which is associated with a Roster by ForeignKey
class Player(models.Model):
    roster = models.ForeignKey(Roster, on_delete=models.CASCADE, null=True, related_name='player_set')
    player_name = models.CharField(max_length=50)
    player_number = models.IntegerField(default=0)
    player_throwing_handedness = models.CharField(max_length=1, default='0')
    player_batting_handedness = models.CharField(max_length=1, default='0')

    def get_absolute_url(self):
        return reverse('tagger:player_details', kwargs={'pk': self.pk})

# our Game model, which is going to have two rosters
class Game(models.Model):
    game_title = models.CharField(max_length=200)
    team1 = models.ForeignKey(Roster, on_delete=models.CASCADE, null=True, related_name='team1')
    team2 = models.ForeignKey(Roster, on_delete=models.CASCADE, null=True, related_name='team2')
    start_time = models.DateTimeField('time started', default=timezone.now())
    date = models.DateTimeField('date', default=timezone.now())

    def get_absolute_url(self):
        return reverse('tagger:game_details', kwargs={'pk': self.pk})

# our Inning model, which allows us to summarize games by inning
class Inning(models.Model):
    half = models.IntegerField() #this is a boolean for top (0) or bottom (1) of the inning
    outs = models.IntegerField()
    runs = models.IntegerField()
    errors = models.IntegerField()
    game = models.ForeignKey(Game, on_delete=models.CASCADE, null=True)

# our atBat model, which relates pitches
class AtBat(models.Model):
    game = models.ForeignKey(Game, on_delete=models.CASCADE, null=True)
    time_stamp = models.DateTimeField('time made')
    result = models.CharField(max_length=200)
    inning = models.ForeignKey(Inning, on_delete=models.CASCADE, null=True)

    def get_absolute_url(self):
        return reverse('tagger:atbat_details', kwargs={'pk': self.pk})

# our pitch model
class Pitch(models.Model):
    pitch_type = models.CharField(max_length=200)
    pitch_call = models.CharField(max_length=200)
    pitch_number = models.IntegerField()
    game = models.ForeignKey(Game, on_delete=models.CASCADE, null=True)

    def get_absolute_url(self):
        return reverse('tagger:pitch_details', kwargs={'pk': self.pk})

tagger_prac/tagger/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django import forms
from django.views.generic.edit import CreateView
from django.views.generic.detail import DetailView
from django.views import generic
from tagger.models import *
from rest_framework import viewsets
from .serializers import *

# test React view

class RosterView(viewsets.ModelViewSet):
    serializer_class = RosterSerializer
    queryset = Roster.objects.all()

class PlayerView(viewsets.ModelViewSet):
    serializer_class = PlayerSerializer
    queryset = Player.objects.all()

class GameView(viewsets.ModelViewSet):
    serializer_class = GameSerializer
    queryset = Game.objects.all()

class InningView(viewsets.ModelViewSet):
    serializer_class = InningSerializer
    queryset = Inning.objects.all()

class AtBatView(viewsets.ModelViewSet):
    serializer_class = AtBatSerializer
    queryset = AtBat.objects.all()

class PitchView(viewsets.ModelViewSet):
    serializer_class = PitchSerializer
    queryset = Pitch.objects.all()

# home page
def home(request):
    return render(request, 'tagger/home.html')

# list the rosters
class roster_index(generic.ListView):
    template_name = 'tagger/roster_index.html'
    context_object_name = 'all_rosters_list'

    def get_queryset(self):
        """all rosters."""
        return Roster.objects.all()

# this lets you see the details of the roster
class roster_details(DetailView):
    model = Roster
    template_name = 'tagger/roster_details.html'

# this makes a new roster to save
class create_roster(CreateView):
    template_name = 'tagger/roster_form.html'
    model = Roster
    fields = ['roster_name', 'num_players']
    #return HttpResponseRedirect(reverse('tagger:player_details', args=))

# list the players
class player_index(generic.ListView):
    template_name = 'tagger/player_index.html'
    context_object_name = 'all_players_list'

    def get_queryset(self):
        """all players."""
        return Player.objects.all()

# this lets you see the details of the player
class player_details(DetailView):
    model = Player
    template_name = 'tagger/player_details.html'

# this makes a new player to save
"""
class create_player(CreateView):
    template_name = 'tagger/player_form.html'
    model = Player
    fields = ['player_name', 'player_height']
    #return HttpResponseRedirect(reverse('tagger:player_details', args=))
"""

class player_form(forms.Form):
    form_player_name = forms.CharField(label='Player Name', max_length=50)
    form_player_number = forms.IntegerField(label='Number')

def add_player(request, roster_id):
    roster = get_object_or_404(Roster, pk=roster_id)
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = player_form(request.POST)
        # check whether it's valid:
        if form.is_valid():
            new_player = Player(player_name=form.cleaned_data['form_player_name'], player_number=form.cleaned_data['form_player_number'])
            new_player.save()
            print("worked\n")
            roster.player_set.add(new_player)
            new_player.roster_set.add(roster)
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            return HttpResponseRedirect(reverse('tagger:roster_details', args=(roster_id,)))

    # if a GET (or any other method) we'll create a blank form
    else:
        form = player_form()

    return render(request, 'player_form.html', {'form': form})


# form for starting a new game
class game_form(forms.Form):
    form_game_title = forms.CharField(label='Game Title', max_length=200)

# starts a new game
def create_game(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = game_form(request.POST)
        # check whether it's valid:
        if form.is_valid():
            new_game = Game(game_title=form.cleaned_data['form_game_title'])
            new_game.start_time = timezone.now()
            new_game.save()
            print("worked\n")
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            return HttpResponseRedirect(reverse('tagger:game_details', args=(new_game.id,)))

    # if a GET (or any other method) we'll create a blank form
    else:
        form = game_form()

    return render(request, 'game_form.html', {'form': form})

class game_details(DetailView):
    model = Game
    template_name = 'tagger/game_details.html'

# list the rosters
class game_index(generic.ListView):
    template_name = 'tagger/game_index.html'
    context_object_name = 'all_games_list'

    def get_queryset(self):
        """all games."""
        return Game.objects.all()
"""
class play_form(forms.Form):
    form_play_type = forms.CharField(label='Play Type', max_length=50)

def add_play(request, game_id):
    game = get_object_or_404(Game, pk=game_id)
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = play_form(request.POST)
        # check whether it's valid:
        if form.is_valid():
            new_play = Play(play_type=form.cleaned_data['form_play_type'], time_stamp=timezone.now())
            new_play.save()
            print("worked\n")
            game.play_set.add(new_play)
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            return HttpResponseRedirect(reverse('tagger:game_details', args=(game_id,)))

    # if a GET (or any other method) we'll create a blank form
    else:
        form = play_form()

    return render(request, 'play_form.html', {'form': form})
"""

tagger_prac/tagger/templates/tagger/game_details.html
<h1>{{ game.game_title }}</h1>
{% if game.play_set.all %}
    <ul>
    {% for play in game.play_set.all %}
        <li><a href="{% url 'tagger:play_details' play.id %}"> {{play.time_stamp}} {{ play.play_type }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p style="color: white">No polls are available.</p>
{% endif %}

<br><br>
<a href="{% url 'tagger:add_play' game.id %}">{{ 'Add a new play' }}</a><br>
<a href="{% url 'tagger:home' %}">{{ 'Return to homepage' }}</a>

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'tagger/homepage.css' %}">

tagger_prac/tagger/templates/tagger/game_index.html
<h1 style="color: white">{{"Games"}}</h1>
{% if all_games_list %}
    <ul>
    {% for game in all_games_list %}
        <li><a href="{% url 'tagger:game_details' game.id %}">{{ game.game_title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p style="color: white">No games are available.</p>
{% endif %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'tagger/homepage.css' %}">

tagger_prac/tagger/templates/tagger/home.html
<h1 style="color: white">Home</h1>
<li><a href="{% url 'tagger:game_index' %}">{{ 'View list of games' }}</a></li><br>
<li><a href="{% url 'tagger:roster_index' %}">{{ 'View list of rosters' }}</a></li><br>
<li><a href="{% url 'tagger:player_index' %}">{{ 'View list of players' }}</a></li><br>

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'tagger/homepage.css' %}">

tagger_prac/tagger/templates/tagger/index.html
{% if all_players_list %}
    <ul>
    {% for player in all_players_list %}
        <li><a href="{% url 'tagger:player_details' player.id %}">{{ player.player_name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

tagger_prac/tagger/templates/tagger/play_details.html
<h1 style="color: white">{{ play.play_type }}</h1>
<h3 style="color: white"><li>Time: {{ play.time_stamp }}</li></h3>
<br><br>
<a href="{% url 'tagger:home' %}">{{ 'Return to homepage' }}</a>

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'tagger/homepage.css' %}">

tagger_prac/tagger/templates/tagger/player_details.html
<h1>{{ player.player_name }}</h1>
<h3><li>Height: {{ player.player_height }}</li></h3>
<br><br>
<a href="{% url 'tagger:home' %}">{{ 'Return to homepage' }}</a>

tagger_prac/tagger/templates/tagger/player_index.html
<h1 style="color: white">{{"Players"}}</h1>
{% if all_players_list %}
    <ul>
    {% for player in all_players_list %}
        <li><a href="{% url 'tagger:player_details' player.id %}">{{ player.player_name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p style="color: white">No players are available.</p>
{% endif %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'tagger/homepage.css' %}">

tagger_prac/tagger/templates/tagger/roster_details.html
<h1 style="color: white;">{{ roster.roster_name }}</h1>
{% if roster.player_set.all %}
    <ul>
    {% for player in roster.player_set.all %}
        <li><a href="{% url 'tagger:player_details' player.id %}">{{ player.player_name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p style="color: white">No players are available.</p>
{% endif %}

<br><br>
<a href="{% url 'tagger:add_player' roster.id %}">{{ 'Add a new player' }}</a><br>
<a href="{% url 'tagger:home' %}">{{ 'Return to homepage' }}</a>

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'tagger/homepage.css' %}">

tagger_prac/tagger/templates/tagger/roster_form.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'tagger/homepage.css' %}">

tagger_prac/tagger/templates/tagger/roster_index.html
<h1 style="color: white">{{"Rosters"}}</h1>
{% if all_rosters_list %}
    <ul>
    {% for roster in all_rosters_list %}
        <li><a href="{% url 'tagger:roster_details' roster.id %}">{{ roster.roster_name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p style="color: white">No rosters are available.</p>
{% endif %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'tagger/homepage.css' %}">